### PR TITLE
Migrate pretty printer to CLJS runtime

### PR DESCRIPTION
**Pull request by comamitc**
See: https://github.com/comamitc/pretty-print.net/issues/33#issuecomment-174069133

The JVM is unsustainable in trivial situations with minimal resources.

### CODE REVIEW

**Comment by comamitc** [comment]
Decided to use just plain `cljs.pprint` but we are sacrificing the comment and macro retainment.   I'll tackle that as a separate issue after this is live with a similar strategy as before but with the logic completely outside of the `pprint` api.

TODO:
- [x] Decommission `jvm` process on server
- [x] Edit codeship build and run script to use the node server

**Comment by comamitc** [comment]
After being exposed to it, I wonder if I can leverage AWS lambda to do this calculation instead of managing our own mode service... Looks like the perfect utility for a process like this... With no data reference.

**Comment by comamitc** [comment]
[`cljfmt`](https://github.com/weavejester/cljfmt) is now a `.cljc` which allows the code to be run in a clojurescript environment. This (with a lot of clean up) now reflects these changes.
- [ ] Question: port all formatters to client side only; remove the need for a server
- [x] Remove settings panel not that these settings do not matter with `cljfmt`
- [x] Resolve merge conflicts

**Comment by shaunlebron** [comment]
Sweet!

**Pull request merged**
